//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapreduceService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceLog
    {
        public int ID { get; set; }
        public string ServiceName { get; set; }
        public string RunTime { get; set; }
        public string Status { get; set; }
        public string Logfile { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
