//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapreduceService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceConfig
    {
        public string ServiceName { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
